ValidatorAddress = "2041D3CBEB5970DE183B8D2CBB9207DE3275659C"

[GenesisDoc]
  GenesisTime = 2019-01-13T12:49:40Z
  ChainName = "BurrowChain_FAB3C1"
  [GenesisDoc.Params]
    ProposalThreshold = 3
  [GenesisDoc.GlobalPermissions]
    [GenesisDoc.GlobalPermissions.Base]
      Perms = "send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | hasRole"
      SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "2041D3CBEB5970DE183B8D2CBB9207DE3275659C"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"C08D5621EA5398A0D3248B67524AFA8210E77DD47C3BDE7B29E552656D3AF993\"}"
    Amount = 99999999999999
    Name = "Full_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "68A25E532599A3FCDC269221E35055B43870B92A"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"BFF56FC8BF49AFC292B1FC686501E2E4AEE0B4DAA34C8243D2FAA730B7DC56C9\"}"
    Amount = 9999999999
    Name = "Participant_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Validators]]
    Address = "2041D3CBEB5970DE183B8D2CBB9207DE3275659C"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"C08D5621EA5398A0D3248B67524AFA8210E77DD47C3BDE7B29E552656D3AF993\"}"
    Amount = 9999999999
    Name = "Full_0"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "2041D3CBEB5970DE183B8D2CBB9207DE3275659C"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"C08D5621EA5398A0D3248B67524AFA8210E77DD47C3BDE7B29E552656D3AF993\"}"
      Amount = 9999999999

[Tendermint]
  Seeds = ""
  SeedMode = false
  PersistentPeers = ""
  ListenAddress = "tcp://0.0.0.0:26656"
  ExternalAddress = ""
  AddrBookStrict = false
  Moniker = ""
  TendermintRoot = ".burrow"
  AuthorizedPeers = ""
  CreateEmptyBlocks = true
  CreateEmptyBlocksInterval = 0

[Execution]
  CallStackMaxDepth = 0
  DataStackInitialCapacity = 1024
  DataStackMaxDepth = 0

[Keys]
  GRPCServiceEnabled = true
  AllowBadFilePermissions = false
  RemoteAddress = ""
  KeysDirectory = ".keys"

[RPC]
  [RPC.Info]
    Enabled = true
    ListenAddress = "tcp://127.0.0.1:26658"
  [RPC.Profiler]
    Enabled = false
    ListenAddress = "tcp://127.0.0.1:6060"
  [RPC.GRPC]
    Enabled = true
    ListenAddress = "127.0.0.1:10997"
  [RPC.Metrics]
    Enabled = false
    ListenAddress = "tcp://127.0.0.1:9102"
    MetricsPath = "/metrics"
    BlockSampleSize = 100

[Logging]
  ExcludeTrace = false
  NonBlocking = false
  [Logging.RootSink]
    [Logging.RootSink.Output]
      OutputType = "stderr"
      Format = "json"

